name: Benchmarks
on: [push]

jobs:
  benchmark:
    name: Performance regression check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.56.1
          override: true
      - name: Run benchmark
        run: cargo bench multiexp
